name: Publish to npm

on:
  push:
    branches: [ main ]  # Trigger on pushes to the master branch (adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest  # Or another compatible runner

    steps:
      - uses: actions/checkout@v3  # Checkout your code

      - name: Use Node.js 18  # Adjust the Node.js version as needed
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm login --registry=https://registry.npmjs.org --legacy-peer-deps

      - name: Publish to npm
        run:  npm publish --access public
