            - name: NPM Publish
  # You may pin to the exact commit or the version.
  # uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c
  uses: JS-DevTools/npm-publish@v3.1.1
  with:
    # The NPM access token to use when publishing
    token: ${{ secrets.NPM_TOKEN }}
          
